"use client";
import { useState, useRef } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { addRecipe } from "@/lib/recipeService";
import { uploadRecipeImage } from "@/lib/uploadService";
import Image from "next/image";
import { auth, db } from "@/lib/firebase";
import { useEffect } from "react";
import { doc, setDoc, collection, addDoc } from "firebase/firestore"; 
import { v4 as uuidv4 } from "uuid";

export default function CreateRecipe() {
  const { data: session } = useSession();
  const router = useRouter();
  const [isSubmitted, setSubmitted] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [previewImage, setPreviewImage] = useState(null);
  const fileInputRef = useRef(null); 
  
  const [ingredients, setIngredients] = useState([{
    quantity: "",
    unit: "",
    name: ""
  }]);

  const unitOptions = [
    "tsp", "tbsp", "cup", "oz", "lb", "g",
    "kg", "ml", "L", "pinch", "dash", "handful",
    "piece", "clove", "slice", "bunch", "can",
    "packet", "to taste", "whole", ""
  ];

  const [recipeData, setRecipe] = useState({
    title: "",
    notes: "",
    cookingTime: 30,
    difficulty: "Medium",
    mealType: "Main Course", 
    instructions: "",
    dietaryOptions: [],
    image: null,
    imageUrl: "/images/background.avif"
  });

  const dietaryOptions = ["Gluten-Free", "Dairy-Free", "Vegan", "Vegetarian"];
  const difficultyOptions = ["Easy", "Medium", "Hard"];
  const mealTypeOptions = ["Main Course", "Side Dish", "Lunch", "Dinner", "Dessert", "Other"];

  const handleChange = (e) => {
    setRecipe({ ...recipeData, [e.target.name]: e.target.value });
  };

  const handleIngredientChange = (index, field, value) => {
    const updatedIngredients = [...ingredients];
    updatedIngredients[index][field] = value;
    setIngredients(updatedIngredients);
  };

  const addIngredient = () => {
    setIngredients([...ingredients, { quantity: "", unit: "", name: "" }]);
  };

  const removeIngredient = (index) => {
    if(ingredients.length == 1) return;
    const updatedIngredients = [...ingredients];
    updatedIngredients.splice(index, 1);
    setIngredients(updatedIngredients);
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];

    if(file) {
      if(!file.type.match('image.*')) {
        alert("Please upload an image file");
        return;
      }

      if(file.size > 1024 * 1024 * 5) {
        alert("Image size must be less than 5MB");
        return;
      }

      setRecipe({...recipeData, image: file});

      const reader = new FileReader();
      reader.onload = (e) => {
        setPreviewImage(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleDietaryToggle = (restriction) => {
    const newRestrictions = [...recipeData.dietaryOptions];
    if (newRestrictions.includes(restriction)) {
      const index = newRestrictions.indexOf(restriction);
      newRestrictions.splice(index, 1);
    } else {
      newRestrictions.push(restriction);
    }
    setRecipe({ ...recipeData, dietaryOptions: newRestrictions });
  }

  const formatIngredients = () => {
    // First, remove any ingredients with empty names
    const ingredientsWithNames = ingredients.filter(ing => ing.name.trim() !== '');
    
    // Then, create a clean copy of each ingredient with trimmed values
    return ingredientsWithNames.map(ing => ({
      quantity: ing.quantity,
      unit: ing.unit,
      name: ing.name.trim()
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if(!recipeData || !recipeData.instructions) {
      alert("Please fill in all required fields.");
      return;
    }

    const formattedIngredients = formatIngredients();
  if (formattedIngredients.length === 0) {
    alert("Please add at least one ingredient");
    return;
  }
    
    try {
      let userId = 'anonymous';
      if (session?.user?.email) {
        userId = session.user.uid;
      }

      let imageUrl = recipeData.imageUrl;

      // Upload image
      if (recipeData.image) {
        setUploadProgress(0);

        imageUrl = await uploadRecipeImage(
          recipeData.image,
          userId,
          null, // No need to pass a specific ID for image folder
          (progress) => setUploadProgress(progress)
        );
      }

      // Prepare the recipe data without the `image` field
      const { image, ...recipeToSubmit } = {
        ...recipeData,
        imageUrl: imageUrl,
        userId: userId, // Include userId in the recipe data
        structuredIngredients: formattedIngredients,
      };

      // Add recipe to the main recipes collection and get the autogenerated ID
      const recipeDocRef = await addDoc(collection(db, "recipes"), recipeToSubmit);
      const recipeId = recipeDocRef.id;

      // Update the recipe data with the autogenerated ID
      recipeToSubmit.id = recipeId;

      // Add recipe to the user's recipes subcollection
      const userRecipeDoc = doc(db, "users", userId, "recipes", recipeId);
      await setDoc(userRecipeDoc, recipeToSubmit);

      setSubmitted(true);
    } catch (error) {
      console.error("Error:", error);
      alert("Failed to save recipe");
    }
  };

  return (
    <div className="p-8 bg-background">
      {!isSubmitted ? (
        <div className="max-w-3xl mx-auto bg-white rounded-lg shadow p-6">
          <h2 className="text-2xl font-bold mb-6 text-gray">Create Your Recipe</h2>
          
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* image upload */}
            <div>
              <label className="block text-gray mb-2">Recipe Image</label>
              <div className="flex flex-col items-center">
                {previewImage ? (
                  <div className="relative w-full h-64 mb-4">
                    <Image
                      src = {previewImage}
                      alt = "recipe preview"
                      fill
                      className = "rounded-lg object-cover"
                      />
                </div>
                ) : (
                  <div className = "w-full h-64 bg-gray/10 rounded-lg flex items-center justify-center mb-4">
                    <p className = "text-gray/50">No image selected</p>    
                  </div>
                  )}
                
                <div className = "flex gap-4">
                  <button
                    type = "button"
                    onClick = {() => fileInputRef.current.click()}
                    className = "px-4 py-2 bg-blue text-white rounded-lg hover:opacity-90"
                    >
                      {previewImage ? "Change Image" : "Select Image"}
                    </button>

                    {previewImage && (
                    <button
                      type="button"
                      onClick={() => {
                        setPreviewImage(null);
                        setRecipe({ ...recipeData, image: null });
                      }}
                      className="px-4 py-2 bg-red text-white rounded-lg hover:opacity-90"
                    >
                      Remove Image
                    </button>
                    )}
                </div>

                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleImageChange}
                  accept="image/*"
                  className="hidden"
                />

                {uploadProgress > 0 && uploadProgress < 100 && (
                  <div className="w-full mt-4">
                    <div className="h-2 bg-gray/20 rounded-full">
                      <div 
                        className="h-full bg-blue rounded-full"
                        style={{ width: `${uploadProgress}%` }}
                      ></div>
                    </div>
                    <p className="text-sm text-gray/70 mt-1">
                      Uploading: {Math.round(uploadProgress)}%
                    </p>
                  </div>
                )}
                </div>
            </div>

            {/* title */}
            <div>
              <label htmlFor="title" className="block text-gray">Recipe Title</label>
              <input
                type="text"
                id="title"
                name="title"
                value={recipeData.title}
                onChange={handleChange}
                placeholder="Phoebe's Coconut-Milk Tomato Pasta"
                required
                className="w-full p-2 border border-gray/20 rounded-lg text-gray"
              />
            </div>
            
            {/* cooking time, difficulty, type */}
            <div className="grid md:grid-cols-3 gap-4">
              <div>
                <label htmlFor="cookingTime" className="block text-gray">Cooking Time (minutes)</label>
                <input
                  type="number"
                  id="cookingTime"
                  name="cookingTime"
                  value={recipeData.cookingTime}
                  onChange={handleChange}
                  required
                  className="w-full p-2 border border-gray/20 rounded-lg text-gray"
                />
              </div>
              
              <div>
                <label htmlFor="difficulty" className="block text-gray">Difficulty</label>
                <select
                  id="difficulty"
                  name="difficulty"
                  value={recipeData.difficulty}
                  onChange={handleChange}
                  className="w-full p-2 border border-gray/20 rounded-lg text-gray"
                >
                  {difficultyOptions.map((option) => (
                    <option key={option} value={option}>{option}</option>
                  ))}
                </select>
              </div>
              
              <div>
                <label htmlFor="mealType" className="block text-gray">Meal Type</label>
                <select
                  id="mealType"
                  name="mealType"
                  value={recipeData.mealType}
                  onChange={handleChange}
                  className="w-full p-2 border border-gray/20 rounded-lg text-gray"
                >
                  {mealTypeOptions.map((option) => (
                    <option key={option} value={option}>{option}</option>
                  ))}
                </select>
              </div>
            </div>
            
            {/* dietary options */}
            <div>
              <label className="block text-gray mb-2">Dietary Friendly Tags</label>
              <div className="flex flex-wrap gap-2">
                {dietaryOptions.map((option) => (
                  <button
                    key={option}
                    type="button"
                    onClick={() => handleDietaryToggle(option)}
                    className={`px-3 py-1 rounded-full text-sm ${
                      recipeData.dietaryOptions.includes(option)
                        ? "bg-blue text-white"
                        : "bg-gray/10 text-gray"
                    }`}
                  >
                    {option}
                  </button>
                ))}
              </div>
            </div>
            
            {/* Add Ingredients Section */}
            <div>
            <label className = "block text-gray font-semibold">Ingredients</label>
              <div className="flex justify-between items-center mb-3">
                
                <button
                  type="button"
                  onClick={addIngredient}
                  className="px-4 py-2 bg-blue text-white rounded-lg hover:opacity-90"
                  >
                    <span className="mr-1">+</span> Add Ingredient
                  </button>
              <div>
                
              <div className="space-y-3 max-h-72 overflow-y-auto p-2 border border-gray/20 rounded-lg"> 
                {ingredients.map((ingredient, index) => (
                  <div key={index} className="flex gap-2 items-center">
                    <input
                      type="text"
                      value={ingredient.quantity}
                      onChange={(e) => handleIngredientChange(index, "quantity", e.target.value)}
                      placeholder="Qty"
                      className="w-16 p-2 border border-gray/20 rounded-lg text-gray"
                    />

                    <select
                      value={ingredient.unit}
                      onChange={(e) => handleIngredientChange(index, "unit", e.target.value)}
                      className="w-24 p-2 border border-gray/20 rounded-lg text-gray"
                      >
                        <option value="">Unit</option>
                        {unitOptions.map((unit) => (
                          <option key={unit} value = {unit}>{unit}</option>
                        ))}
                    </select>

                    <input
                      type="text"
                      value={ingredient.name}
                      onChange={(e) => handleIngredientChange(index, "name", e.target.value)}
                      placeholder="Ingredient Name"
                      className="flex-grow p-2 border border-gray/20 rounded-lg text-gray"
                      required={index === 0} // Make the first ingredient required
                    />

                    <button
                      type="button"
                      onClick={() => removeIngredient(index)}
                      className="p-2 text-red hover:bg-red/10 rounded-full"
                      disabled={ingredients.length === 1} // Disable if only one ingredient left
                      >
                        ✕
                      </button>
                    </div>
                ))}
              </div>
            </div>
            </div>
            </div>
            
            <div>
              <label htmlFor="instructions" className="block text-gray mb-1">Instructions</label>
              <textarea
                id="instructions"
                name="instructions"
                value={recipeData.instructions}
                onChange={handleChange}
                placeholder="How do you make this recipe?"
                required
                rows="5"
                className="w-full p-2 border border-gray/20 rounded-lg text-gray"
              ></textarea>
            </div>
            
            <div>
              <label htmlFor="notes" className="block text-gray mb-1">Notes (optional)</label>
              <textarea
                id="notes"
                name="notes"
                value={recipeData.notes}
                onChange={handleChange}
                placeholder=""
                rows="3"
                className="w-full p-2 border border-gray/20 rounded-lg text-gray"
              ></textarea>
            </div>
            
            {/* submit button */}
            <div className="flex justify-end">
              <button
                type="submit"
                className="px-6 py-2 bg-red text-white rounded-lg hover:opacity-90 transition"
              >
                Save Recipe
              </button>
            </div>
          </form>
        </div>
      ) : (
        <div className="text-center bg-white rounded-lg p-8">
          <h2 className="text-2xl font-bold text-gray mb-4">Recipe Submitted!</h2>
          <p className="mb-6 text-gray/80">Your recipe &quot;{recipeData.title}&quot; has been successfully created.</p>
          <div className="flex gap-4 justify-center">
            <button 
              onClick={() => router.push("/main/recipes")}
              className="px-4 py-2 bg-blue text-white rounded-lg hover:opacity-90"
            >
              View All Recipes
            </button>
          </div>
        </div>
      )}
    </div>
  );
}