import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
// Removed import './styles/fonts.css';
import Navbar from "@/components/Navbar";
import ClientSessionProvider from "./ClientSessionProvider";

//this is the global layout

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientSessionProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar /> 
          <main className="flex-grow p-6">{children}</main>
        </body>
      </html>
    </ClientSessionProvider>
  );
}